name: Mirror to GitLab and run CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror to gitlab and trigger CI
      uses: HackerShohag/gitlab-mirror@master
      with:
        args: "https://gitlab.com/shohag-ut-apps/RAVEN_Downloader.git"
      env:
        FOLLOW_TAGS: "true"
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "HackerShohag"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "44762632"
        GITHUB_TOKEN: ${{ secrets.GITHUBA_TOKEN }}
        GITHUB_NAME: "Abdullah AL Shohag"
        GITHUB_EMAIL: "HackerShohag@outlook.com"
