.MODEL SMALL
.STACK 100H
.DATA
	MSG1   DB "ENTER THE FIRST DIGIT: $"
	MSG2   DB 0DH,0AH,"ENTER THE SECOND DIGIT: $"
	MSG3   DB 0DH,0AH,"THE SUBSTRACTION IS $"
	NUM1   DB ?
	NUM2   DB ?
	RESULT DB ?
.CODE
MAIN PROC
	     MOV AX, @DATA
	     MOV DS, AX

	; INPUT NUM1
	     LEA DX, MSG1
	     MOV AH, 9
	     INT 21H

	     MOV AH, 1
	     INT 21H
	     MOV NUM1, AL
	; INPUT NUM2
	     LEA DX, MSG2
	     MOV AH, 9
	     INT 21H

	     MOV AH, 1
	     INT 21H
	     MOV NUM2, AL

	; SUBSTRACTION
	     MOV AL, NUM1
	     MOV BL, NUM2
	     SUB AL, BL
	     MOV RESULT, AL

	     LEA DX, MSG3
	     MOV AH, 9
	     INT 21H

	     MOV AH, 2
	     MOV DL, RESULT
	     ADD DL, '0'
	     INT 21H

	; RETURN
	     MOV AH, 4CH
	     INT 21H

MAIN ENDP
END MAIN